// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSwtoCZDBGFzZptdkpEpVR8p6Dc684lZ0',
    appId: '1:241843390302:web:2e9d46f4737cc6343031cf',
    messagingSenderId: '241843390302',
    projectId: 'tasks-13e48',
    authDomain: 'tasks-13e48.firebaseapp.com',
    storageBucket: 'tasks-13e48.firebasestorage.app',
    measurementId: 'G-TWKSEJYNLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAZTUw1T9NsAq3q2sLxOzjHd1_WAtyIf4',
    appId: '1:241843390302:android:c1ff8155b391f16e3031cf',
    messagingSenderId: '241843390302',
    projectId: 'tasks-13e48',
    storageBucket: 'tasks-13e48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrJ3Y77UNNqNsw6xDv5RmIQSCaclIe7Ds',
    appId: '1:241843390302:ios:db1de39ae91606ff3031cf',
    messagingSenderId: '241843390302',
    projectId: 'tasks-13e48',
    storageBucket: 'tasks-13e48.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrJ3Y77UNNqNsw6xDv5RmIQSCaclIe7Ds',
    appId: '1:241843390302:ios:db1de39ae91606ff3031cf',
    messagingSenderId: '241843390302',
    projectId: 'tasks-13e48',
    storageBucket: 'tasks-13e48.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSwtoCZDBGFzZptdkpEpVR8p6Dc684lZ0',
    appId: '1:241843390302:web:b6b4f528335afbdf3031cf',
    messagingSenderId: '241843390302',
    projectId: 'tasks-13e48',
    authDomain: 'tasks-13e48.firebaseapp.com',
    storageBucket: 'tasks-13e48.firebasestorage.app',
    measurementId: 'G-5LRX1Y60R7',
  );
}
